// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import UtmBannerController from "./utm_banner_controller"
application.register("utm-banner", UtmBannerController)
