# 감사사례 TRUST REPAIR — 원문 출처 없는 171건을 «가상 예방 시나리오»로 표시 (2026-09-17 전수감사 G-13)
#
# 운영 읽기 전용 실측(2026-09-17 19:45 덤프): 원문 URL·발행기관이 전혀 없는 사례 171건
#   · SILMU_RECONSTRUCTED_CASE 110 («재구성 사례» — 원문을 재구성한 것처럼 읽힘)
#   · UNVERIFIED 61 («출처 추가 검증 필요» — 실사건이 출처 확인만 남은 것처럼 읽힘)
#   · 171건 모두 기관을 ○○·▲▲·★★·◎◎ 등으로 가리고 인물·일시·금액·처분을 창작한 서사
#     (처분명 포함 163 · 연월 포함 110 — 예: «H씨 감봉 2개월 및 중복 수령액 564,500원 전액 환수»)
#   · 163건에 «법령 근거 검증» 배지 — 법령명이 해석된다는 뜻뿐인데 사례 검증으로 읽힘
# 원칙: 확실하지 않으면 라벨을 먼저 강등한다. 본문(창작 처분·일시) 정정은 별도 배치.
# 원문 문서가 있는 재구성(경기도교육청 사례집 62·서울시교육청 6)과 실제 감사결과 18건은 대상이 아니다.
# 인벤토리 = 하네스 tasks/silmu-full-audit-rebuild-0917/artifacts/19_AUDIT_CASE_TRUST_INVENTORY_0917.json
# DRY_RUN=1 이면 쓰지 않는다. 대상 행에 원문 URL 이 생겼으면 전체 롤백한다.

marker = AuditCaseProvenanceClassifier::SIMULATED_MARKER
note = "#{marker}: 원문 출처 없는 창작 시나리오(기관 익명·인물·일시·금액·처분 창작) → «가상 예방 시나리오». 원문을 확보한 경우에만 재분류."

slugs = [
  "accommodation-allowance-false-claim",
  "accounting-data-falsification",
  "accounting-evidence-missing",
  "accounting-officer-dual-role-fraud",
  "additional-contract-limit-001",
  "annual-leave-compensation-double-payment",
  "bid-bond-not-submitted",
  "bid-deposit-001",
  "bid-evaluation-criteria-missing",
  "bid-failure-negotiation-001",
  "bid-period-insufficient",
  "bid-qualification-001",
  "bid-qualification-excessive",
  "bid-qualification-review-omitted",
  "bid-rebid-condition-change",
  "bid-two-envelope-violation",
  "bid-unfair-spec",
  "budget-appropriation-mistake",
  "budget-carryover-violation",
  "budget-document-error",
  "budget-execution-before-approval",
  "budget-execution-no-receipt",
  "budget-execution-wrong-account",
  "budget-item-wrong-category",
  "budget-item-wrong-travel",
  "budget-lapse-improper-carryover",
  "budget-misuse",
  "budget-overrun",
  "budget-timing-violation",
  "budget-transfer-limit-violation",
  "budget-transfer-without-council-approval",
  "budget-unauthorized-transfer",
  "business-expense-personal-use",
  "cash-management-failure",
  "completion-inspection-violation",
  "completion-payment-checklist-001",
  "contingency-fund-misuse",
  "contingency-fund-purpose-misuse",
  "contract-amount-adjustment-001",
  "contract-guarantee-exemption-wrong",
  "contract-guarantee-not-collected",
  "contract-late-execution",
  "contract-missing-special-terms",
  "contract-no-guarantee-forfeiture",
  "contract-period-extension-illegal",
  "contract-termination-no-notice",
  "contract-verbal-agreement",
  "contract-wrong-party",
  "cost-calculation-indirect-cost-overrate",
  "debt-management-negligence",
  "defect-warranty-no-deposit",
  "defect-warranty-short-period",
  "defective-construction-cover-up",
  "defective-inspection",
  "design-change-unapproved",
  "direct-production-confirm-missing",
  "disciplinary-action-request-delay",
  "domestic-travel-transport-overclaim",
  "double-booking-budget",
  "double-entry-error",
  "e-bidding-error-switched-to-paper",
  "e-bidding-offline-processed",
  "e-procurement-bypass-narajangteo",
  "emergency-budget-violation",
  "emergency-contract-unjustified",
  "estimated-price-leak",
  "estimated-price-leak-incident",
  "estimated-price-no-research",
  "expenditure-over-budget",
  "false-private-contract-reason",
  "family-allowance-ineligible-payment",
  "financial-statement-error",
  "foreign-travel-private-tourism",
  "goods-inspection-failure",
  "goods-selection-committee-bypassed",
  "guideline-abolished-project-budget",
  "guideline-excess-budget-compilation",
  "holiday-bonus-pre-retirement-payment",
  "improper-advance-payment",
  "information-disclosure-delay",
  "inspection-by-requester",
  "inspection-delayed",
  "inspection-procedure-omission",
  "inspector-qualification-violation",
  "joint-contract-nominal",
  "late-penalty-not-imposed",
  "late-penalty-wrong-rate",
  "leave-of-absence-employment-unreported",
  "local-bond-excess-issuance",
  "long-term-contract-annual-omission",
  "lowest-bid-rate-violation-award",
  "mas-contract-non-listed-product",
  "multiple-price-manipulation",
  "national-local-contract-law-mix",
  "national-subsidy-purpose-misuse",
  "non-budgetary-funds-violation",
  "official-leave-false-reason",
  "overpayment-not-recovered",
  "parental-leave-benefit-double-receipt",
  "payment-advance-misuse",
  "payment-before-inspection",
  "payment-delay-no-interest",
  "payment-no-deduction-penalty",
  "payment-without-completion",
  "penalty-reduction-unauthorized",
  "performance-bonus-score-manipulation",
  "performance-guarantee-waiver-loss",
  "price-escalation-below-threshold",
  "private-contract-no-quote",
  "private-contract-no-reason",
  "private-contract-over-limit",
  "private-contract-price-no-negotiation",
  "private-contract-purpose-mismatch",
  "private-contract-retroactive",
  "private-contract-same-vendor",
  "private-contract-split",
  "private-contract-split-over-limit",
  "progress-payment-over-claimed",
  "property-disposal-no-appraisal",
  "public-procurement-mandatory-bid-bypassed",
  "qualification-failure-wrong-award",
  "quote-collection-same-vendor-double",
  "reserve-fund-violation",
  "retirement-allowance-service-period-error",
  "revenue-collection-delay",
  "safety-violation-construction",
  "school-budget-deadline-violation",
  "school-budget-without-committee-review",
  "secondment-return-delay",
  "settlement-report-delayed",
  "sick-leave-days-exceeded",
  "silmu-2026-concurrent-external-lecture-no-report",
  "silmu-2026-concurrent-for-profit-business",
  "silmu-2026-concurrent-unauthorized",
  "silmu-2026-overtime-fixed-share-no-prorate",
  "silmu-2026-overtime-post-approval",
  "silmu-2026-overtime-travel-overlap",
  "silmu-2026-overtime-weekday-no-deduction",
  "silmu-2026-position-suspension-bribery-investigation",
  "silmu-2026-position-suspension-criminal-prosecution",
  "silmu-2026-position-suspension-discipline-pending",
  "silmu-2026-position-suspension-incompetence-dismissal",
  "silmu-2026-position-suspension-senior-officer-review",
  "silmu-2026-reinstatement-expired-no-notice",
  "silmu-2026-reinstatement-late-notice",
  "silmu-2026-reinstatement-step-recalc-missing",
  "silmu-2026-reinstatement-unfair-placement",
  "single-quote-exceeds-limit",
  "small-amount-intentional-split",
  "software-dev-misclassified-as-goods",
  "spec-price-integration-violation",
  "special-leave-holiday-miscalculation",
  "split-contract-to-avoid-bidding",
  "split-order-monthly-to-avoid-bidding",
  "subcontract-below-cost",
  "subcontract-direct-payment-denied",
  "subcontract-no-notice",
  "subcontract-payment-delay",
  "subcontract-unauthorized-re-sub",
  "subcontract-whole-transfer",
  "subsidy-settlement-false-report",
  "substitution-material-unapproved",
  "supervision-absent",
  "supplementary-budget-before-council",
  "supplementary-budget-violation",
  "travel-expense-double-claim",
  "travel-expense-settlement-no-receipt",
  "unit-price-contract-quantity-exceeded",
  "vehicle-travel-allowance-distance-fraud",
  "welfare-point-cash-conversion",
  "year-end-settlement-duplicate-deduction"
]

dry = ENV["DRY_RUN"] == "1"
changed = 0
missing = []
ActiveRecord::Base.transaction do
  slugs.each do |slug|
    ac = AuditCase.find_by(slug: slug)
    next missing << slug unless ac
    next if ac.source_type == "SILMU_SIMULATED_CASE" && ac.verification_note.to_s.include?(marker)
    raise "[simulated-label] 원문 URL 존재 — 가상 판정 불가: #{slug}" if ac.public_source_url.present?

    changed += 1
    next if dry

    ac.update_columns(
      source_type: "SILMU_SIMULATED_CASE",
      is_reconstructed: true,
      verification_status: "RECONSTRUCTED",
      verification_note: [ ac.verification_note.presence, note ].compact.join("\n"),
      updated_at: Time.current
    )
  end
end

puts "  [simulated-label] #{"DRY_RUN " if dry}changed=#{changed} missing=#{missing.size} #{missing.first(5).join(',')}"
