# 구기준 법령 수치 잔존 정정 — 지체상금·수의계약 한도·여비·정액급식비·낙찰하한율 (2026-09-17 전수감사 G-10·G-11·G-12·G-07, 15_STALE_VALUE_SWEEP)
#
# 원문: 지방계약법 시행규칙 제75조(공사 1000분의 0.5 · 물품 0.8 · 수리·가공·대여·용역 등 1.3 · 운송·보관·양곡가공 2.5, 임대차 요율 없음) ·
#   국가계약법 시행규칙 제75조(공사 1천분의 0.5 · 물품 0.75 · 수리·가공·대여·용역 1.25) · 지방계약법 시행령 제25조 제1항 제5호(종합공사 4억 · 전문공사 2억 · 그 밖 1억6천만 · 물품·용역 2천만 · 소기업·소상공인 1억) ·
#   같은 영 제30조 제1항 제2호(1인 견적 2천만원 이하, 청년창업·여성·장애인·사회적기업 등 5천만원 이하) · 제42조(적격심사, 300억 이상은 제42조의3), 제42조의2 삭제<2016. 1. 15.>, 제43조·제43조의2 없음 ·
#   제50조 제1항 제1호(계약금액 5천만원 이하 계약서 생략) · 공무원 여비 규정 별표 2(2026. 6. 30.: 일비·식비 25,000 · 숙박비 실비 상한) ·
#   공무원수당 등에 관한 규정 제18조(정액급식비 월 16만원) · 지방자치단체 입찰 및 계약 집행기준 제5장 제3절(2인 견적 수의 물품·용역 88%/90%) ·
#   낙찰하한율 구간·시행일: 행안부 예규 낙찰자 결정기준 제325호(2025. 7. 1. 시행) · 재정경제부 계약예규 적격심사기준(2026. 1. 30. 이후 공고분) [2차 근거: 감사 기록 04b].
# AuditCase#132 는 요율 정정에 맞춰 금액(14억원 × 0.5/1,000 × 40일 = 2,800만원, 3년 누적 4,800만원)을 행 전체에서 다시 계산했다.
# 각 old 는 해당 필드(jsonb 는 문자열 leaf 합계)에 정확히 1회 있어야 하고, 하나라도 어긋나면 전체 롤백한다. 이미 new 이면 건너뛴다. DRY_RUN=1 이면 쓰지 않는다.

edits = [
  [ AuditCase, "penalty-reduction-unauthorized", "detail",
    "| 지연배상금률 | 1/1,000 (공사, 1일당) |",
    "| 지연배상금률 | 0.5/1,000 (공사, 1일당, 지방계약법 시행규칙 제75조) |" ],
  [ AuditCase, "penalty-reduction-unauthorized", "detail",
    "| **발생 지연배상금** | **5,600만원** |",
    "| **발생 지연배상금** | **2,800만원** |" ],
  [ AuditCase, "penalty-reduction-unauthorized", "detail",
    "지연배상금 5,600만원을 부과하여야",
    "지연배상금 2,800만원을 부과하여야" ],
  [ AuditCase, "penalty-reduction-unauthorized", "detail",
    "- 2023년: 지연배상금 5,600만원 임의 감면 (이번 사건)",
    "- 2023년: 지연배상금 2,800만원 임의 감면 (이번 사건)" ],
  [ AuditCase, "penalty-reduction-unauthorized", "detail",
    "**3년 누적 임의 감면액: 7,600만원**",
    "**3년 누적 임의 감면액: 4,800만원**" ],
  [ AuditCase, "penalty-reduction-unauthorized", "detail",
    "감면 처리한 지연배상금 5,600만원 전액",
    "감면 처리한 지연배상금 2,800만원 전액" ],
  [ AuditCase, "penalty-reduction-unauthorized", "detail",
    "군에 지연배상금 5,600만원 납부",
    "군에 지연배상금 2,800만원 납부" ],
  [ AuditCase, "penalty-reduction-unauthorized", "issue",
    "지연배상금 5,600만원이 발생",
    "지연배상금 2,800만원이 발생" ],
  [ AuditCase, "penalty-reduction-unauthorized", "action_taken",
    "지연배상금 5,600만원 변상 명령",
    "지연배상금 2,800만원 변상 명령" ],
  [ Topic, "penalty-reduction-procedure", "practical_tips",
    "### ⚠️ 지체상금 요율 (국가계약법 기준)\n- **공사**: 계약금액의 1,000분의 1 (0.1%/일)\n- **물품 제조·구매**: 계약금액의 1,000분의 1.5 (0.15%/일)",
    "### ⚠️ 지체상금 요율 (국가계약법 시행규칙 제75조 기준)\n- **공사**: 계약금액의 1,000분의 0.5 (0.05%/일)\n- **물품 제조·구매**: 계약금액의 1,000분의 0.75 (0.075%/일)" ],
  [ Topic, "penalty-reduction-procedure", "qa_content",
    "1억 x 0.1% x 10일 = 100만원",
    "1억 x 0.05% x 10일 = 50만원" ],
  [ Topic, "late-penalty", "regulation_content",
    "| 운송·보관 등 | 1/1,000 | **2.5/1,000** |\n| 임대차 | 1/1,000 | **1/1,000** |\n",
    "| 운송·보관 등 | 2.5/1,000 | **2.5/1,000** |\n\n※ 임대차 요율은 따로 없음 — 물품 대여는 수리·가공·대여·용역 요율(국가 1.25/1,000, 지방 1.3/1,000) 적용\n" ],
  [ Topic, "late-penalty", "qa_content",
    "- 임대차: 계약금액의 **1/1,000** (1일당)\n",
    "- 임대차: 별도 요율 없음 — 물품 대여는 계약금액의 **1.3/1,000** (1일당)\n" ],
  [ Topic, "late-penalty", "practical_tips",
    "적용 상금률 확인 (공사/물품·용역/임대차)",
    "적용 상금률 확인 (공사/물품/용역 등/운송·보관)" ],
  [ AuditCase, "late-penalty-wrong-rate", "lesson",
    "운송·보관: 1,000분의 2.5 / 임대차: 1,000분의 1 (시행규칙 제75조)",
    "운송·보관·양곡가공: 1,000분의 2.5 (시행규칙 제75조 — 임대차 요율은 따로 없고 물품 대여는 1,000분의 1.3)" ],
  [ AuditCase, "late-penalty-wrong-rate", "checkpoints",
    "운송 2.5/1,000, 임대차 1.0/1,000 (시행규칙 제75조)",
    "운송 2.5/1,000 (시행규칙 제75조, 대여는 1.3/1,000)" ],
  [ AuditCase, "late-penalty-wrong-rate", "checkpoints",
    "계약유형(공사/물품·용역/임대차)을 정확히 구분",
    "계약유형(공사/물품/용역 등/운송·보관)을 정확히 구분" ],
  [ Topic, "travel-expense", "quick_stats",
    "20,000원/일",
    "25,000원/일" ],
  [ Topic, "travel-expense", "quick_stats",
    "숙박비 (정액)",
    "숙박비 (실비 상한)" ],
  [ Topic, "travel-expense", "qa_content",
    "숙박비는 정액 지급이 원칙입니다. 실제 지출액이 기준액보다 적더라도 기준액을 지급받습니다.",
    "숙박비는 실비 지급이 원칙으로, 상한액(서울 10만원·광역시 8만원·그 밖 7만원) 이내에서 실제 지출액을 지급받습니다(공무원 여비 규정 별표 2)." ],
  [ Topic, "travel-expense", "commentary",
    "• 일비: 직급별 정액<br>\n• 숙박비: 실비 정산 (영수증 필수)<br>\n• 식비: 일비에 포함 또는 별도 지급",
    "• 일비: 1일 25,000원 정액 (직급 구분 없음)<br>\n• 숙박비: 실비 정산 (영수증 필수)<br>\n• 식비: 일비와 별도로 1일 25,000원 (공무원 여비 규정 별표 2)" ],
  [ Topic, "travel-expense", "regulation_content",
    "| 일비 | 정액 (별표 2, 직급별) |",
    "| 일비 | 정액 1일 25,000원 (별표 2) |" ],
  [ Topic, "travel-expense", "regulation_content",
    "| 식비 | 정액 (별표 2, 직급별) |",
    "| 식비 | 정액 1일 25,000원 (별표 2) |" ],
  [ Guide, "travel-expense-complete-2", "rich_media",
    "정액 지급 — 영수증 없이 직급별로 정해진 금액을 출장 1일당 지급.",
    "정액 지급 — 영수증 없이 일비·식비 각 25,000원을 출장 1일당 지급(직급 구분 없음, 공무원 여비 규정 별표 2)." ],
  [ Guide, "travel-expense-complete-2", "rich_media",
    "약 2만원/일. 매년 개정 가능하므로 소속 기관 현행 기준 확인 필수.",
    "2만5천원/일 — 현행 별표 2에는 직급별 식비 차등이 없습니다." ],
  [ Guide, "travel-expense-complete-1", "sections",
    "일비·식비는 직급별 정해진 금액으로 지급 (영수증 불필요)",
    "일비·식비는 1일 각 25,000원으로 지급 (직급 구분 없음, 영수증 불필요)" ],
  [ Guide, "travel-expense-complete-1", "rich_media",
    "정액 지급 — 직급별로 정해진 금액을 영수증 없이 출장 1일당 지급.",
    "정액 지급 — 일비·식비 각 25,000원을 영수증 없이 출장 1일당 지급(직급 구분 없음)." ],
  [ AuditCase, "single-quote-exceeds-limit", "checkpoints",
    "2천만원 이하라도 5백만원 초과 시 2인 이상 견적 필수",
    "2천만원 이하는 1인 견적 가능(청년창업·여성·장애인·사회적기업 등은 5천만원 이하, 시행령 제30조 제1항 제2호)" ],
  [ Topic, "private-contract-justification", "interpretation_content",
    "**[회신]** 추정 가격이 500만 원 미만인 경우에는 1개사 견적만으로도 수의계약이 가능합니다. 다만, 500만 원 이상 2천만 원(공사는 3천만 원) 미만의 경우에는 2개사 이상 견적을 징구하여야 합니다.",
    "**[회신]** 추정가격이 2천만원 이하(청년창업기업·여성기업·장애인기업·사회적기업 등은 5천만원 이하)인 경우에는 1인으로부터 받은 견적서로 수의계약을 할 수 있으므로, 추정가격 300만원이면 1개사 견적으로 가능합니다(지방계약법 시행령 제30조 제1항 제2호). 이 금액을 넘는 소액 수의계약은 2인 이상으로부터 견적서를 받아야 합니다(같은 항 본문)." ],
  [ Topic, "private-contract-justification", "regulation_content",
    "- 2인 이상으로부터 견적서 징구 (추정 가격 5백만 원 이상인 경우)",
    "- 2인 이상으로부터 견적서 징구 (추정가격 2천만원 초과인 경우, 청년창업·여성·장애인·사회적기업 등은 5천만원 초과 — 시행령 제30조 제1항)" ],
  [ Guide, "suui-contract-complete-3", "sections",
    "※ 500만 원 이하는 1개 업체 견적도 가능, 500만 원 초과~2천만 원 이하는 2개 이상 필수",
    "※ 2천만 원 이하는 1개 업체 견적도 가능(청년창업·여성·장애인·사회적기업 등은 5천만 원 이하), 이를 넘는 수의계약은 2개 이상 필수 (시행령 제30조 제1항)" ],
  [ Guide, "suui-contract-complete-3", "sections",
    "500만 원 이하: 1개 업체 견적서로도 가능",
    "2천만 원 이하: 1개 업체 견적서로도 가능 (시행령 제30조 제1항 제2호)" ],
  [ Guide, "suui-contract-complete-3", "sections",
    "500만 원 초과: 2개 이상 업체에서 견적 징구 필수",
    "2천만 원 초과(소기업·소상공인 특례 등): 2개 이상 업체에서 견적 징구 필수" ],
  [ Guide, "suui-contract-complete-3", "sections",
    "(500만원 초과 시 2개 이상)",
    "(2천만원 초과 시 2개 이상)" ],
  [ Guide, "suui-contract-complete-3", "sections",
    "500만 원 초과 시 반드시 2개 업체 이상 견적을",
    "2천만 원(특례 기업 5천만 원) 초과 수의계약은 반드시 2개 업체 이상 견적을" ],
  [ Guide, "suui-contract-complete-3", "sections",
    "500만원 초과 소액 수의계약에서 2개 이상 견적이",
    "2천만원 초과 소액 수의계약에서 2개 이상 견적이" ],
  [ Guide, "suui-contract-complete-3", "rich_media",
    "    C -->|이하| E{500만원 초과?}\n    E -->|아니오| F[1개 업체 견적 가능]\n    E -->|예| G[2개 이상 업체 견적 필수]\n    F --> H[품의서 기안 및 결재]\n    G --> H\n",
    "    C -->|이하| F[1개 업체 견적 가능]\n    F --> H[품의서 기안 및 결재]\n" ],
  [ Guide, "suui-contract-complete-3", "rich_media",
    "추정가격 500만 원 초과 ~ 2천만 원 이하. 500만 원 이하는 1개 업체 견적 가능.",
    "추정가격 2천만 원 초과(청년창업·여성·장애인·사회적기업 등은 5천만 원 초과). 그 이하는 1개 업체 견적 가능(시행령 제30조 제1항 제2호)." ],
  [ Guide, "suui-contract-complete-3", "rich_media",
    "500만 원 이하",
    "2천만 원 이하" ],
  [ Guide, "suui-contract-complete-3", "rich_media",
    "500만 원 초과~2천만 원 이하",
    "2천만 원 초과 (소액 수의 특례)" ],
  [ Guide, "suui-contract-complete-9", "sections",
    "견적 미징구: 500만원 초과에서 1개 업체 견적만 받음",
    "견적 미징구: 2천만원 초과에서 1개 업체 견적만 받음" ],
  [ Guide, "suui-contract-complete-9", "rich_media",
    "G{500만원 초과 시 2개?}",
    "G{2천만원 초과 시 2개?}" ],
  [ Guide, "suui-contract-complete-9", "rich_media",
    "견적 미징구 — 500만원 초과 계약에서",
    "견적 미징구 — 2천만원 초과 계약에서" ],
  [ Guide, "suui-contract-complete-9", "rich_media",
    "견적 미징구 (500만원 초과 시)",
    "견적 미징구 (2천만원 초과 시)" ],
  [ AuditCase, "goe-2021-private-contract-s2b-mismatch", "lesson",
    "| 공사 수의계약 한도 | 2억원 이하 (기본) — 종합공사 4억·전문공사 2억 등 행안부 예규 세분화 |",
    "| 공사 수의계약 한도 | 종합공사 4억원·전문공사 2억원·그 밖의 공사 1억6천만원 이하 (시행령 제25조 제1항 제5호 가목) |" ],
  [ AuditCase, "goe-2021-split-private-contracts", "lesson",
    "| 공사 수의계약 한도 | 2억원 이하 (기본) — 종합공사 4억·전문공사 2억 등 행안부 예규 세분화 |",
    "| 공사 수의계약 한도 | 종합공사 4억원·전문공사 2억원·그 밖의 공사 1억6천만원 이하 (시행령 제25조 제1항 제5호 가목) |" ],
  [ AuditCase, "goe-2021-split-private-contracts", "lesson",
    "입찰 의무 기준(일반 업체 2천만원·공사 2억원)",
    "입찰 의무 기준(일반 업체 2천만원·종합공사 4억원·전문공사 2억원)" ],
  [ AuditCase, "goe-2021-football-team-extension-contract", "lesson",
    "| 물품·용역 1인 견적 수의계약 | 2천만원 이하 | 2천만원 이하 (동일) |",
    "| 물품·용역 1인 견적 수의계약 | 2천만원 이하 | 5천만원 이하 (청년창업·여성·장애인·사회적기업 등, 시행령 제30조 제1항 제2호 단서) |" ],
  [ AuditCase, "goe-2021-football-team-extension-contract", "lesson",
    "| 공사 수의계약 한도 (기본) | 2억원 이하 | 동일 |\n| 공사 예규 세분화 한도 | 종합공사 4억 / 전문공사 2억 / 기타 1.6억 등 (행안부 예규에서 별도 상향) |",
    "| 공사 수의계약 한도 | 종합공사 4억원 / 전문공사 2억원 / 그 밖의 공사 1억6천만원 이하 (시행령 제25조 제1항 제5호 가목) | 동일 |" ],
  [ AuditCase, "private-contract-over-limit", "lesson",
    "- 물품·용역: 추정가격 2천만원 이하(1인 견적), 1억원 이하(2인 이상 견적)",
    "- 물품·용역: 추정가격 2천만원 이하(1인 견적). 소기업·소상공인과 계약하면 2천만원 초과 1억원 이하도 수의계약 가능(2인 이상 견적, 시행령 제25조 제1항 제5호 라목)" ],
  [ Topic, "small-amount-contract", "qa_content",
    "- **공사:** 2천만원 이하 (1인 견적), 2억원 이하 (2인 견적)",
    "- **공사:** 2천만원 이하 (1인 견적), 종합공사 4억원·전문공사 2억원·그 밖의 공사 1억6천만원 이하 (2인 견적, 시행령 제25조 제1항 제5호 가목)" ],
  [ Topic, "small-amount-contract", "qa_content",
    "**A:** 추정가격 **5천만원 이하**(공사 1억원 이하)인 경우 계약서 작성을 생략할 수 있습니다.",
    "**A:** 계약금액 **5천만원 이하**(공사·물품·용역 구분 없음)인 경우 계약서 작성을 생략할 수 있습니다(시행령 제50조 제1항 제1호)." ],
  [ Guide, "private-contract-amount-guide", "sections",
    "공사: 추정가격 2억원 이하 → 수의계약 가능",
    "종합공사: 추정가격 4억원 이하 → 수의계약 가능 (그 밖의 공사 1억6천만원 이하, 시행령 제25조 제1항 제5호 가목)" ],
  [ Guide, "private-contract-amount-guide", "sections",
    "전문공사: 추정가격 1억원 이하 → 수의계약 가능",
    "전문공사: 추정가격 2억원 이하까지 수의계약 가능" ],
  [ Topic, "contract-execution", "qa_content",
    "**A:** 추정가격 **5천만원 이하**(물품·용역) 또는 **1억원 이하**(공사), 전기·가스·수도 공급계약",
    "**A:** 계약금액 **5천만원 이하**(공사·물품·용역 구분 없음, 시행령 제50조 제1항 제1호), 전기·가스·수도 공급계약" ],
  [ Topic, "contract-execution", "faqs",
    "물품·용역은 추정가격 5천만원 이하, 공사는 1억원 이하일 때 생략 가능합니다.",
    "공사·물품·용역 구분 없이 계약금액 5천만원 이하일 때 생략 가능합니다(시행령 제50조 제1항 제1호)." ],
  [ Guide, "hr-welfare-complete-7", "sections",
    "동일 금액(현행 월 14만 원)이",
    "동일 금액(월 16만원, 공무원수당 등에 관한 규정 제18조)이" ],
  [ Guide, "hr-welfare-complete-7", "rich_media",
    "현행 월 14만 원 균일 지급.",
    "월 16만원 균일 지급(공무원수당 등에 관한 규정 제18조)." ],
  [ Topic, "lowest-bid-rate", "summary",
    "2026년 1월 2일부터 기존 87.745%에서 상향 조정되었습니다.",
    "추정가격 10억원 미만 공사 기준이며, 지방자치단체는 2025년 7월 1일(국가계약은 2026년 1월 30일 이후 공고분)부터 기존 87.745%에서 2%p 상향됐습니다." ],
  [ Topic, "lowest-bid-rate", "quick_stats",
    "2026.1.2 이후",
    "10억 미만 공사 · 지방 2025.7.1~" ],
  [ Topic, "lowest-bid-rate", "quick_stats",
    "2025.12.31까지",
    "지방 2025.6.30 공고분까지" ],
  [ Topic, "lowest-bid-rate", "quick_stats",
    "공사에만 적용",
    "2인 견적 수의 88%(2천만원 이하 90%)" ],
  [ Topic, "lowest-bid-rate", "quick_stats",
    "미적용",
    "별도 기준" ],
  [ Topic, "lowest-bid-rate", "faqs",
    "2026년 1월 2일부터 예정가격의 89.745%입니다.",
    "추정가격 10억원 미만 공사는 예정가격의 89.745%입니다(지방 2025.7.1 시행 · 10억원 이상 50억원 미만 88.745% · 50억원 이상 100억원 미만 87.495%)." ],
  [ Topic, "lowest-bid-rate", "faqs",
    "2025년 12월 31일까지는 87.745%였고, 2026년 1월 2일부터 89.745%로 상향 조정되었습니다.",
    "지방자치단체 공사는 행정안전부 예규 「지방자치단체 입찰시 낙찰자 결정기준」 개정(제325호)으로 2025년 7월 1일부터, 국가계약은 재정경제부 계약예규 「적격심사기준」 개정으로 2026년 1월 30일 이후 입찰공고분부터 89.745%(10억원 미만 기준)로 상향됐습니다." ],
  [ Topic, "lowest-bid-rate", "faqs",
    "아니요. 낙찰하한율은 공사 입찰에만 적용되며, 물품·용역 입찰에는 적용되지 않습니다.",
    "공사 비율이 그대로 적용되지는 않고 물품·용역은 별도 기준을 따릅니다. 예를 들어 2인 이상 견적 수의계약에서는 예정가격 대비 88%(추정가격 2천만원 이하 90%) 이상 견적 중 최저가 순으로 계약상대자를 정합니다(「지방자치단체 입찰 및 계약 집행기준」 제5장 제3절)." ],
  [ Topic, "lowest-bid-rate", "faqs",
    "지방계약법 시행령 제42조(낙찰자의 결정)의 위임에 따라 「입찰 및 계약집행기준」 제7조에서 정합니다.",
    "지방계약법 시행령 제42조 제2항에 따라 행정안전부장관이 정하는 심사기준인 「지방자치단체 입찰시 낙찰자 결정기준」(행정안전부 예규)의 입찰가격 평점산식에서 정해집니다." ],
  [ Topic, "lowest-bid-rate", "rule_content",
    "<p><strong>입찰 및 계약집행기준 제7조 (낙찰하한율)</strong></p>\n<div style=\"padding:12px 16px; background:#dbeafe; border-left:4px solid #3b82f6; border-radius:8px; margin:12px 0;\">\n① 공사의 낙찰하한율은 <strong style=\"font-size:18px; background:#dcfce7; padding:4px 10px; border-radius:6px;\">89.745%</strong>로 한다. (2026년 1월 2일 시행)\n</div>\n<div style=\"padding:12px 16px; background:#fef3c7; border-left:4px solid #f59e0b; border-radius:8px; margin:12px 0;\">\n<strong>⚠️ 2026년 1월 변경사항</strong><br>\n기존: 87.745% (2025.12.31까지)<br>\n변경: 89.745% (2026.1.2부터)\n</div>\n<div style=\"padding:12px 16px; background:#eff6ff; border-radius:8px; margin:12px 0; font-size:14px;\">\n② 물품 및 용역 계약에는 낙찰하한율을 적용하지 아니한다.<br>\n③ 낙찰하한율 미만으로 입찰한 경우 무효로 처리한다.\n</div>\n<div style=\"padding:12px; background:#f3f4f6; border-radius:8px; margin:8px 0; font-size:13px;\">\n<strong>계산 예시:</strong><br>\n예정가격 1억원, 낙찰하한율 89.745%<br>\n→ 최저가격 = 1억원 × 89.745% = 8,974만 5천원<br>\n→ 8,974만 5천원 미만 입찰은 무효\n</div>",
    "<p><strong>「지방자치단체 입찰시 낙찰자 결정기준」(행정안전부 예규) — 공사 적격심사 낙찰하한율</strong></p>\n<div style=\"padding:12px 16px; background:#dbeafe; border-left:4px solid #3b82f6; border-radius:8px; margin:12px 0;\">\n추정가격 10억원 미만 공사: <strong style=\"font-size:18px; background:#dcfce7; padding:4px 10px; border-radius:6px;\">89.745%</strong><br>\n10억원 이상 50억원 미만: 88.745% · 50억원 이상 100억원 미만: 87.495%\n</div>\n<div style=\"padding:12px 16px; background:#fef3c7; border-left:4px solid #f59e0b; border-radius:8px; margin:12px 0;\">\n<strong>⚠️ 상향 시점 (종전 대비 2%p)</strong><br>\n지방자치단체: 2025.7.1 시행 (행정안전부 예규 제325호, 종전 87.745%)<br>\n국가계약: 2026.1.30 이후 입찰공고분 (재정경제부 계약예규 「적격심사기준」)\n</div>\n<div style=\"padding:12px 16px; background:#eff6ff; border-radius:8px; margin:12px 0; font-size:14px;\">\n낙찰하한율은 예규 조문에 비율로 적힌 값이 아니라, 적격심사 입찰가격 평점산식에서 역산되는 값입니다. 물품·용역은 별도 기준이 적용됩니다.\n</div>\n<div style=\"padding:12px; background:#f3f4f6; border-radius:8px; margin:8px 0; font-size:13px;\">\n<strong>계산 예시 (단순 계산):</strong><br>\n예정가격 1억원, 낙찰하한율 89.745%<br>\n→ 1억원 × 89.745% = 8,974만 5천원\n</div>" ],
  [ Topic, "lowest-bid-rate", "decree_content",
    "<p><strong>지방계약법 시행령 제42조 (낙찰자의 결정)</strong></p>\n<div style=\"padding:12px 16px; background:#dbeafe; border-left:4px solid #3b82f6; border-radius:8px; margin:12px 0;\">\n① 지방자치단체의 장 또는 계약담당자는 입찰에 부친 사항에 대하여 예정가격 이하로서 최저가격으로 입찰한 자를 낙찰자로 한다. 다만, 제42조제2항에 따른 적격심사(계약이행능력 심사)를 실시하는 경우에는 그러하지 아니하다.\n</div>\n<div style=\"padding:12px 16px; background:#eff6ff; border-radius:8px; margin:12px 0; font-size:14px;\">\n② 제1항에도 불구하고 예산의 효율적 집행과 공사의 품질보전을 위하여 <strong style=\"background:#fef3c7; padding:2px 6px; border-radius:4px;\">예정가격 이하로서 최저가격 이상의 가격으로 입찰한 자</strong>를 낙찰자로 할 수 있다. 이 경우 <strong>최저가격은 행정안전부장관이 정하여 고시하는 낙찰하한율에 따른다.</strong>\n</div>\n<div style=\"padding:12px; background:#f3f4f6; border-radius:8px; margin:8px 0; font-size:13px;\">\n<strong>핵심:</strong> 낙찰하한율은 행정안전부장관이 예규로 정합니다. 2026년 1월 2일부터 공사는 89.745%로 상향 조정되었습니다.\n</div>",
    "<p><strong>지방계약법 시행령 제42조 (재정지출의 부담이 되는 입찰에서의 낙찰자 결정)</strong></p>\n<div style=\"padding:12px 16px; background:#dbeafe; border-left:4px solid #3b82f6; border-radius:8px; margin:12px 0;\">\n① 지방자치단체의 장 또는 계약담당자는 재정지출의 부담이 되는 입찰에 있어서는 예정가격 이하로서 최저가격으로 입찰한 자부터 순서대로 해당 계약이행능력을 심사하여 낙찰자를 결정한다. 다만, 추정가격이 300억원 이상인 공사입찰의 경우에는 제42조의3에 따라 낙찰자를 결정한다. (제1항 제1호 요지)\n</div>\n<div style=\"padding:12px 16px; background:#eff6ff; border-radius:8px; margin:12px 0; font-size:14px;\">\n② 제1항에 따른 계약이행능력의 심사는 해당 입찰자의 이행실적, 기술능력, 재무상태, 과거 계약이행 성실도, … 및 입찰가격 등을 종합적으로 고려하여 <strong style=\"background:#fef3c7; padding:2px 6px; border-radius:4px;\">행정안전부장관이 정하는 심사기준</strong>에 따라 적격 여부를 심사하며, 그 심사 결과 적격하다고 인정되는 경우 그 입찰자를 낙찰자로 결정한다.\n</div>\n<div style=\"padding:12px; background:#f3f4f6; border-radius:8px; margin:8px 0; font-size:13px;\">\n<strong>핵심:</strong> 낙찰하한율은 시행령 조문에 직접 적혀 있지 않고, 제2항의 심사기준(「지방자치단체 입찰시 낙찰자 결정기준」)의 입찰가격 평점산식에서 정해집니다. 지방자치단체는 2025년 7월 1일 시행 개정으로 추정가격 10억원 미만 공사가 89.745%입니다. (제42조의2는 2016. 1. 15. 삭제)\n</div>" ],
  [ Topic, "lowest-bid-rate", "regulation_content",
    "(2026년 전 구간 2%p 상향)",
    "(2025년 7월 1일 시행 개정으로 2%p 상향)" ],
  [ Topic, "lowest-bid-rate", "regulation_content",
    "#### 공사 계약 낙찰하한율 (2026년 상향 기준)",
    "#### 공사 계약 낙찰하한율 (2025.7.1 상향 기준)" ],
  [ Topic, "lowest-bid-rate", "regulation_content",
    "심사점수 합격(공사 85점, 물품·용역 92점)",
    "적격심사 통과점수(공사 추정가격 100억원 미만 95점, 100억원 이상 300억원 미만 92점)" ],
  [ Topic, "lowest-bid-rate", "practical_tips",
    "- 추정가격 **300억원 이상** 공사: 최저가낙찰제 원칙 적용\n- 2016년 이후 대부분 종합심사낙찰제로 전환 추세\n",
    "- 추정가격 **300억원 이상** 공사: 시행령 제42조의3에 따라 지방자치단체에 가장 유리하게 입찰한 자를 낙찰자로 결정 (최저가낙찰제 아님)\n- 300억원 미만 공사: 시행령 제42조에 따른 적격심사\n" ],
  [ Topic, "lowest-bid-rate", "qa_content",
    "최저가낙찰제는 주로 추정가격 300억원 이상의 대형 공사에 적용되며, 최근에는 종합심사낙찰제·적격심사제 등 다양한 방식으로 분화되었습니다.",
    "지방자치단체 공사는 추정가격 300억원 이상이면 시행령 제42조의3(지방자치단체에 가장 유리하게 입찰한 자), 그 미만이면 제42조에 따른 적격심사로 낙찰자를 결정하므로 최저가낙찰제가 기본 방식이 아닙니다." ],
  [ Topic, "lowest-bid-rate", "commentary",
    "2. 2026년 변경사항 (87.745% → 89.745%)",
    "2. 상향 시점 (87.745% → 89.745%)" ],
  [ Topic, "lowest-bid-rate", "commentary",
    "<strong>⚠️ 중요 변경:</strong> 2026년 1월 2일부터 2% 상향 조정<br>\n기존: 87.745% (2025년까지)<br>\n변경: 89.745% (2026년부터)<br>\n적용: 2026.1.2 이후 공고된 입찰부터 적용",
    "<strong>⚠️ 중요 변경:</strong> 추정가격 10억원 미만 공사 기준 2%p 상향 (87.745% → 89.745%)<br>\n지방자치단체: 2025년 7월 1일 시행 (행정안전부 예규 제325호)<br>\n국가계약: 2026년 1월 30일 이후 입찰공고분 (재정경제부 계약예규 「적격심사기준」)<br>\n10억원 이상 50억원 미만 88.745% · 50억원 이상 100억원 미만 87.495%" ],
  [ Topic, "lowest-bid-rate", "commentary",
    "<strong>❌ 오류:</strong> 물품·용역 계약에도 낙찰하한율 적용<br>\n<strong>✅ 정답:</strong> 낙찰하한율은 <strong>공사만</strong> 적용됩니다. 물품·용역은 최저가 낙찰입니다.",
    "<strong>❌ 오류:</strong> 물품·용역에도 공사 낙찰하한율(89.745%)을 그대로 적용<br>\n<strong>✅ 정답:</strong> 물품·용역은 <strong>별도 기준</strong>입니다. 예: 2인 이상 견적 수의계약 88%(추정가격 2천만원 이하 90%)" ],
  [ Topic, "lowest-bid-rate", "commentary",
    "<strong>❌ 오류:</strong> 적격심사 대상 공사도 낙찰하한율 적용<br>\n<strong>✅ 정답:</strong> 적격심사는 95점 이상 중 최저가이므로 낙찰하한율 적용 <strong>안 됨</strong>",
    "<strong>❌ 오류:</strong> 적격심사 대상 공사에는 낙찰하한율이 없다<br>\n<strong>✅ 정답:</strong> 낙찰하한율은 적격심사 입찰가격 평점산식에서 역산되는 값으로 적격심사 공사에 <strong>적용됨</strong>" ],
  [ Topic, "lowest-bid-rate", "commentary",
    "<strong>❌ 오류:</strong> 2025년 입찰에 89.745% 적용<br>\n<strong>✅ 정답:</strong> 공고일 기준으로 적용됩니다. 2025.12.31 이전 공고는 87.745%",
    "<strong>❌ 오류:</strong> 국가계약과 지방계약의 상향 시점을 같은 날로 봄<br>\n<strong>✅ 정답:</strong> 공고일 기준으로 적용됩니다. 지방은 2025.7.1 시행, 국가는 2026.1.30 이후 공고분부터 89.745%" ],
  [ Topic, "lowest-bid-rate", "commentary",
    "2026.1.2 전후 공고 구분 필수",
    "지방 2025.7.1 · 국가 2026.1.30 전후 공고 구분 필수" ],
  [ Topic, "lowest-bid-rate", "commentary",
    "• 공사 낙찰하한율: 89.745% (2026.1.2부터)<br>\n• 물품·용역은 낙찰하한율 없음<br>\n• 적격심사 대상은 낙찰하한율 미적용<br>",
    "• 공사 낙찰하한율: 10억원 미만 89.745% (지방 2025.7.1 · 국가 2026.1.30 공고분부터)<br>\n• 물품·용역은 별도 기준 적용<br>\n• 낙찰하한율은 적격심사 가격평점 산식에서 나옴<br>" ],
  [ Topic, "lowest-bid-rate", "law_content",
    "지방계약법 시행령 제42조 (낙찰자의 결정), 입찰 및 계약집행기준 제7조 (낙찰하한율)",
    "지방계약법 시행령 제42조 (재정지출의 부담이 되는 입찰에서의 낙찰자 결정), 「지방자치단체 입찰시 낙찰자 결정기준」(행정안전부 예규)" ],
  [ Guide, "bid-complete-5", "sections",
    "낙찰하한율 있음 (89.745%).",
    "낙찰하한율 있음 (추정가격 10억원 미만 89.745% 등 구간별)." ],
  [ Guide, "bid-complete-5", "sections",
    "(89.745%, 2026.1.2 시행 기준)",
    "(10억원 미만 공사 89.745% — 지방 2025.7.1 · 국가 2026.1.30 공고분부터)" ]
]

count_in = lambda do |value, needle|
  case value
  when String then value.scan(needle).size
  when Array  then value.sum { |v| count_in.call(v, needle) }
  when Hash   then value.values.sum { |v| count_in.call(v, needle) }
  else 0
  end
end

replace_in = lambda do |value, from, to|
  case value
  when String then value.gsub(from) { to }
  when Array  then value.map { |v| replace_in.call(v, from, to) }
  when Hash   then value.transform_values { |v| replace_in.call(v, from, to) }
  else value
  end
end

dry = ENV["DRY_RUN"] == "1"
changes = 0
ActiveRecord::Base.transaction(requires_new: true) do
  edits.group_by { |klass, slug, field, _, _| [ klass, slug, field ] }.each do |(klass, slug, field), list|
    record = klass.find_by(slug: slug)
    next unless record

    original = record.read_attribute(field)
    value = original
    list.each do |_, _, _, old, new|
      next if count_in.call(value, new).positive? && count_in.call(value, old).zero?
      raise "[stale-legal-values] fingerprint missing: #{klass.name}/#{slug}/#{field}: #{old[0, 40]}" unless count_in.call(value, old) == 1

      value = replace_in.call(value, old, new)
      changes += 1
    end
    record.update_columns(field => value, updated_at: Time.current) if value != original && !dry
  end
end
puts "  [stale-legal-values] #{"DRY_RUN " if dry}changes=#{changes}"
