module HomeHelper
  # Tailwind JIT는 동적 보간 클래스를 감지하지 못하므로
  # 색상별 완전한 클래스 문자열을 미리 정의해 룩업 방식으로 사용
  TOPIC_COLOR_CLASSES = {
    "indigo"  => {
      icon_lg:      "bg-indigo-100 text-indigo-600 group-hover:bg-indigo-600 group-hover:text-white",
      icon_sm:      "bg-indigo-50 text-indigo-600 group-hover:bg-indigo-600 group-hover:text-white",
      icon_base:    "bg-indigo-50 text-indigo-600",
      title:        "group-hover:text-indigo-600",
      badge:        "text-indigo-600 bg-indigo-50 border-indigo-100",
      hero:         "text-indigo-400 group-hover:text-indigo-300",
      step_border:  "hover:border-indigo-300",
      step_num:     "text-indigo-700",
      hub_border:   "hover:border-indigo-100",
      hub_title:    "group-hover:text-indigo-700",
      hub_count:    "text-indigo-600 bg-indigo-50",
      hub_link:     "text-indigo-600 group-hover:text-indigo-700",
      hub_arrow:    "text-indigo-400 group-hover:text-indigo-600",
    },
    "violet"  => {
      icon_lg:      "bg-violet-100 text-violet-600 group-hover:bg-violet-600 group-hover:text-white",
      icon_sm:      "bg-violet-50 text-violet-600 group-hover:bg-violet-600 group-hover:text-white",
      icon_base:    "bg-violet-50 text-violet-600",
      title:        "group-hover:text-violet-600",
      badge:        "text-violet-600 bg-violet-50 border-violet-100",
      hero:         "text-violet-400 group-hover:text-violet-300",
      step_border:  "hover:border-violet-300",
      step_num:     "text-violet-700",
      hub_border:   "hover:border-violet-100",
      hub_title:    "group-hover:text-violet-700",
      hub_count:    "text-violet-600 bg-violet-50",
      hub_link:     "text-violet-600 group-hover:text-violet-700",
      hub_arrow:    "text-violet-400 group-hover:text-violet-600",
    },
    "amber"   => {
      icon_lg:      "bg-amber-100 text-amber-600 group-hover:bg-amber-600 group-hover:text-white",
      icon_sm:      "bg-amber-50 text-amber-600 group-hover:bg-amber-600 group-hover:text-white",
      icon_base:    "bg-amber-50 text-amber-600",
      title:        "group-hover:text-amber-600",
      badge:        "text-amber-600 bg-amber-50 border-amber-100",
      hero:         "text-amber-400 group-hover:text-amber-300",
      step_border:  "hover:border-amber-300",
      step_num:     "text-amber-700",
      hub_border:   "hover:border-amber-100",
      hub_title:    "group-hover:text-amber-700",
      hub_count:    "text-amber-600 bg-amber-50",
      hub_link:     "text-amber-600 group-hover:text-amber-700",
      hub_arrow:    "text-amber-400 group-hover:text-amber-600",
    },
    "emerald" => {
      icon_lg:      "bg-emerald-100 text-emerald-600 group-hover:bg-emerald-600 group-hover:text-white",
      icon_sm:      "bg-emerald-50 text-emerald-600 group-hover:bg-emerald-600 group-hover:text-white",
      icon_base:    "bg-emerald-50 text-emerald-600",
      title:        "group-hover:text-emerald-600",
      badge:        "text-emerald-600 bg-emerald-50 border-emerald-100",
      hero:         "text-emerald-400 group-hover:text-emerald-300",
      step_border:  "hover:border-emerald-300",
      step_num:     "text-emerald-700",
      hub_border:   "hover:border-emerald-100",
      hub_title:    "group-hover:text-emerald-700",
      hub_count:    "text-emerald-600 bg-emerald-50",
      hub_link:     "text-emerald-600 group-hover:text-emerald-700",
      hub_arrow:    "text-emerald-400 group-hover:text-emerald-600",
    },
    "blue"    => {
      icon_lg:      "bg-blue-100 text-blue-600 group-hover:bg-blue-600 group-hover:text-white",
      icon_sm:      "bg-blue-50 text-blue-600 group-hover:bg-blue-600 group-hover:text-white",
      icon_base:    "bg-blue-50 text-blue-600",
      title:        "group-hover:text-blue-600",
      badge:        "text-blue-600 bg-blue-50 border-blue-100",
      hero:         "text-blue-400 group-hover:text-blue-300",
      step_border:  "hover:border-blue-300",
      step_num:     "text-blue-700",
      hub_border:   "hover:border-blue-100",
      hub_title:    "group-hover:text-blue-700",
      hub_count:    "text-blue-600 bg-blue-50",
      hub_link:     "text-blue-600 group-hover:text-blue-700",
      hub_arrow:    "text-blue-400 group-hover:text-blue-600",
    },
    "rose"    => {
      icon_lg:      "bg-rose-100 text-rose-600 group-hover:bg-rose-600 group-hover:text-white",
      icon_sm:      "bg-rose-50 text-rose-600 group-hover:bg-rose-600 group-hover:text-white",
      icon_base:    "bg-rose-50 text-rose-600",
      title:        "group-hover:text-rose-600",
      badge:        "text-rose-600 bg-rose-50 border-rose-100",
      hero:         "text-rose-400 group-hover:text-rose-300",
      step_border:  "hover:border-rose-300",
      step_num:     "text-rose-700",
      hub_border:   "hover:border-rose-100",
      hub_title:    "group-hover:text-rose-700",
      hub_count:    "text-rose-600 bg-rose-50",
      hub_link:     "text-rose-600 group-hover:text-rose-700",
      hub_arrow:    "text-rose-400 group-hover:text-rose-600",
    },
    "slate"   => {
      icon_lg:      "bg-slate-100 text-slate-600 group-hover:bg-slate-600 group-hover:text-white",
      icon_sm:      "bg-slate-50 text-slate-600 group-hover:bg-slate-600 group-hover:text-white",
      icon_base:    "bg-slate-50 text-slate-600",
      title:        "group-hover:text-slate-600",
      badge:        "text-slate-600 bg-slate-50 border-slate-100",
      hero:         "text-slate-400 group-hover:text-slate-300",
      step_border:  "hover:border-slate-300",
      step_num:     "text-slate-700",
      hub_border:   "hover:border-slate-100",
      hub_title:    "group-hover:text-slate-700",
      hub_count:    "text-slate-600 bg-slate-50",
      hub_link:     "text-slate-600 group-hover:text-slate-700",
      hub_arrow:    "text-slate-400 group-hover:text-slate-600",
    },
    "pink"    => {
      icon_lg:      "bg-pink-100 text-pink-600 group-hover:bg-pink-600 group-hover:text-white",
      icon_sm:      "bg-pink-50 text-pink-600 group-hover:bg-pink-600 group-hover:text-white",
      icon_base:    "bg-pink-50 text-pink-600",
      title:        "group-hover:text-pink-600",
      badge:        "text-pink-600 bg-pink-50 border-pink-100",
      hero:         "text-pink-400 group-hover:text-pink-300",
      step_border:  "hover:border-pink-300",
      step_num:     "text-pink-700",
      hub_border:   "hover:border-pink-100",
      hub_title:    "group-hover:text-pink-700",
      hub_count:    "text-pink-600 bg-pink-50",
      hub_link:     "text-pink-600 group-hover:text-pink-700",
      hub_arrow:    "text-pink-400 group-hover:text-pink-600",
    },
    "teal"    => {
      icon_lg:      "bg-teal-100 text-teal-600 group-hover:bg-teal-600 group-hover:text-white",
      icon_sm:      "bg-teal-50 text-teal-600 group-hover:bg-teal-600 group-hover:text-white",
      icon_base:    "bg-teal-50 text-teal-600",
      title:        "group-hover:text-teal-600",
      badge:        "text-teal-600 bg-teal-50 border-teal-100",
      hero:         "text-teal-400 group-hover:text-teal-300",
      step_border:  "hover:border-teal-300",
      step_num:     "text-teal-700",
      hub_border:   "hover:border-teal-100",
      hub_title:    "group-hover:text-teal-700",
      hub_count:    "text-teal-600 bg-teal-50",
      hub_link:     "text-teal-600 group-hover:text-teal-700",
      hub_arrow:    "text-teal-400 group-hover:text-teal-600",
    },
    "orange"  => {
      icon_lg:      "bg-orange-100 text-orange-600 group-hover:bg-orange-600 group-hover:text-white",
      icon_sm:      "bg-orange-50 text-orange-600 group-hover:bg-orange-600 group-hover:text-white",
      icon_base:    "bg-orange-50 text-orange-600",
      title:        "group-hover:text-orange-600",
      badge:        "text-orange-600 bg-orange-50 border-orange-100",
      hero:         "text-orange-400 group-hover:text-orange-300",
      step_border:  "hover:border-orange-300",
      step_num:     "text-orange-700",
      hub_border:   "hover:border-orange-100",
      hub_title:    "group-hover:text-orange-700",
      hub_count:    "text-orange-600 bg-orange-50",
      hub_link:     "text-orange-600 group-hover:text-orange-700",
      hub_arrow:    "text-orange-400 group-hover:text-orange-600",
    },
  }.freeze

  # 뷰에서 tc(color, :icon_sm) 형태로 호출
  def tc(color, key)
    (TOPIC_COLOR_CLASSES[color.to_s] || TOPIC_COLOR_CLASSES["indigo"])[key]
  end
end
